version: '3'
services:
  app:
    build: .
    command: /bin/sh -c "cd /srv/app && chmod a+x ./composer.phar && php ./composer.phar install && php ./composer.phar install && apache2-foreground"
    image: breakout-docker
    ports:
      - ${BREAKOUT_PORT:-9001}:80
    volumes:
      - ./src:/srv/app